# ===== Información general de la app =====
spring.application.name=vinos_api
application.title=Proyecto de Venta de Vinos
application.description=API para gestionar la venta de vinos en linea
application.version=1.0.0

# ===== Servidor =====
server.port=${SERVER_PORT}

# ===== Base de datos MySQL =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== Spring Boot Config =====
spring.main.allow-bean-definition-overriding=true
spring.sql.init.mode=never

# ===== Devtools =====
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ===== Logging =====
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.security=ERROR
logging.level.io.jsonwebtoken=ERROR

# ===== JWT =====
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===== Archivos =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
fotosUsuarios.url=${APP_URL_BASE}

# ===== URLs configurables =====
# URL base de la aplicación (local, dev o prod)
app.url.base=${APP_URL_BASE}
# Endpoint de recuperación de contraseña
app.recovery.endpoint=${APP_RECOVERY_ENDPOINT}

# ===== Configuración de email (ejemplo con Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
